layout_spectrum: 0.01792115
color:
  saturation: 0.6827957
  brandStrength: 0.06145914
  lightness: 0.107702
  rhythmicContrast: 0.9032258
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.2150538
name: Gabriela Sánchez
